<?php
namespace Modules\Attendance\Controllers;

use App\Notifications\AdminChannelServices;
use Modules\Animals\Models\Animal;
use Modules\Animals\Models\AnimalTranslation;
use Modules\Booking\Events\BookingUpdatedEvent;
use Modules\Booking\Models\Enquiry;
use Modules\Car\Hook;
use Modules\Core\Events\CreatedServicesEvent;
use Modules\Core\Events\UpdatedServiceEvent;
use Modules\FrontendController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Modules\Location\Models\Location;
use Modules\Core\Models\Attributes;
use Modules\Booking\Models\Booking;
use Modules\User\Models\Plan;

class ManageAnimalController extends FrontendController
{
    protected $animalClass;
    protected $animalTranslationClass;
    protected $animalTermClass;
    protected $attributesClass;
    protected $locationClass;
    protected $bookingClass;
    protected $enquiryClass;

    public function __construct(Animal $animalClass,AnimalTranslation $animalTranslationClass, Location $locationClass,Attributes $attributesClass,Booking $bookingClass, Enquiry $enquiryClass)
    {
        parent::__construct();
        $this->locationClass = $locationClass;
        $this->animalClass = $animalClass;
        $this->attributesClass = $attributesClass;
        $this->animalTranslationClass = $animalTranslationClass;
//        $this->animalTermClass = $animalTermClass;
        $this->bookingClass = $bookingClass;
        $this->enquiryClass = $enquiryClass;
    }

    public function callAction($method, $parameters)
    {
        if(!Animal::isEnable())
        {
            return redirect('/');
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }
    public function manageAnimal(Request $request)
    {
        $userHotelId = get_user_hotel_id();
        $this->checkPermission('animal_view');

        $list_animals = $this->animalClass::query()
            ->join('bc_hotel_animals as bha', function ($join) use ($userHotelId) {
                $join->on('bha.animal_id', '=', 'bc_animals.id')
                    ->where('bha.hotel_id', '=', $userHotelId);
            })
            ->select([
                'bc_animals.*',
                'bha.status as animal_status'
            ])
            ->orderBy('bc_animals.id', 'desc');

        $data = [
            'rows' => $list_animals->paginate(5),
            'animal_list' =>  $this->animalClass::whereDoesntHave('hotels', function($q) use ($userHotelId) {$q->where('bc_hotel_animals.hotel_id', $userHotelId);})->get(),
            'breadcrumbs'        => [
                [
                    'name' => __('Manage Animals'),
                    'url'  => route('animal.vendor.index')
                ],
                [
                    'name'  => __('All'),
                    'class' => 'active'
                ],
            ],
            'page_title'         => __("Manage Animals"),
        ];

        return view('Animal::frontend.manageAnimal.index', $data);
    }

    public function recovery(Request $request)
    {
        $this->checkPermission('animal_view');
        $user_id = Auth::id();
        $list_tour = $this->animalClass::onlyTrashed()->where("author_id", $user_id)->orderBy('id', 'desc');
        $data = [
            'rows' => $list_tour->paginate(5),
            'recovery'           => 1,
            'breadcrumbs'        => [
                [
                    'name' => __('Manage Animals'),
                    'url'  => route('animal.vendor.index')
                ],
                [
                    'name'  => __('Recovery'),
                    'class' => 'active'
                ],
            ],
            'page_title'         => __("Recovery Animals"),
        ];
        return view('Animal::frontend.manageAnimal.index', $data);
    }

    public function restore($id)
    {
        $this->checkPermission('animal_delete');
        $user_id = Auth::id();
        $query = $this->animalClass::onlyTrashed()->where("author_id", $user_id)->where("id", $id)->first();
        if(!empty($query)){
            $query->restore();
            event(new UpdatedServiceEvent($query));

        }
        return redirect(route('animal.vendor.recovery'))->with('success', __('Restore animal success!'));
    }

    public function create(Request $request)
    {
        $this->checkPermission('animal_create');
        $row = new $this->animalClass();
        $data = [
            'row'           => $row,
            'translation' => new $this->animalTranslationClass(),
            'animal_location' => $this->locationClass::where("status","publish")->get()->toTree(),
            'attributes'    => $this->attributesClass::where('service', 'animal')->get(),
            'breadcrumbs'        => [
                [
                    'name' => __('Manage Animals'),
                    'url'  => route('animal.vendor.index')
                ],
                [
                    'name'  => __('Create'),
                    'class' => 'active'
                ],
            ],
            'page_title'         => __("Create Animals"),
        ];
        return view('Animal::frontend.manageAnimal.detail', $data);
    }


    public function store( Request $request, $id ){
        if(is_demo_mode()){
            return redirect()->back()->with('danger',__("DEMO MODE: can not add data"));
        }
        if($id>0){
            $this->checkPermission('animal_update');
            $row = $this->animalClass::find($id);

            if (empty($row)) {
                return redirect(route('animal.vendor.index'));
            }

            if($row->author_id != Auth::id() and !$this->hasPermission('animal_manage_others'))
            {
                return redirect(route('animal.vendor.index'));
            }
        }else{
            $this->checkPermission('animal_create');

            $row = new $this->animalClass();
            $row->status = "publish";


            if(setting_item("animal_vendor_create_service_must_approved_by_admin", 0)){
                $row->status = "pending";
            }
            $row->author_id = Auth::id();
        }
        $dataKeys = [
            'title',
            'content',
            'price',
            'is_instant',
            'video',
            'faqs',
            'image_id',
            'banner_image_id',
            'gallery',
            'location_id',
            'hotel_id',
            'address',
            'map_lat',
            'map_lng',
            'map_zoom',
            'number',
            'price',
            'is_featured',
            'default_state',
            'ical_import_url'
        ];

        $row->fillByAttr($dataKeys,$request->input());
        $hotelId = get_user_hotel_id();
        $row->hotel_id = $hotelId;

//        if(!auth()->user()->checkUserPlan() and $row->status == "publish") {
//            return redirect(route('user.plan'));
//        }

        $res = $row->saveOriginOrTranslation($request->input('lang'),true);

        if ($res) {
            if(!$request->input('lang') or is_default_lang($request->input('lang'))) {
//                $this->saveTerms($row, $request);
            }
            do_action(Hook::AFTER_SAVING,$row,$request);
            if($id > 0 ){
                event(new UpdatedServiceEvent($row));
                return back()->with('success',  __('Animal updated') );
            }else{
                event(new CreatedServicesEvent($row));
                return redirect(route('animal.vendor.edit',['id'=>$row->id]))->with('success', __('Animal created') );
            }
        }
    }

    public function saveTerms($row, $request)
    {
        if (empty($request->input('terms'))) {
            $this->animalTermClass::where('target_id', $row->id)->delete();
        } else {
            $term_ids = $request->input('terms');
            foreach ($term_ids as $term_id) {
                $this->animalClass::firstOrCreate([
                    'term_id' => $term_id,
                    'target_id' => $row->id
                ]);
            }
            $this->animalTermClass::where('target_id', $row->id)->whereNotIn('term_id', $term_ids)->delete();
        }
    }

    public function edit(Request $request, $id)
    {
        $this->checkPermission('animal_update');
        $user_id = Auth::id();
        $row = $this->animalClass::where("author_id", $user_id);
        $row = $row->find($id);
        if (empty($row)) {
            return redirect(route('animal.vendor.index'))->with('warning', __('Animal not found!'));
        }
        $translation = $row->translate($request->query('lang'));
        $data = [
            'translation'    => $translation,
            'row'           => $row,
            'car_location' => $this->locationClass::where("status","publish")->get()->toTree(),
            'attributes'    => $this->attributesClass::where('service', 'animal')->get(),
//            "selected_terms" => $row->terms->pluck('term_id'),
            'breadcrumbs'        => [
                [
                    'name' => __('Manage Animals'),
                    'url'  => route('animal.vendor.index')
                ],
                [
                    'name'  => __('Edit'),
                    'class' => 'active'
                ],
            ],
            'page_title'         => __("Edit Animals"),
        ];
        return view('Animal::frontend.manageAnimal.detail', $data);
    }

    public function bulkEAttach(Request $request)
    {
        $this->checkPermission('animal_update');
        $animalId = $request->input('animal_id');
        $userHotelId = get_user_hotel_id();

        $animal = $this->animalClass::find($animalId);

        if (!$animal) {
            return redirect()->back()->with('error', __('Not Found'));
        }

        $animal->hotels()->syncWithoutDetaching([$userHotelId]);
        return response()->json(['success' => true, 'message' => __('Attach success!')]);
    }

    public function bulkEDetach($id)
    {
        $this->checkPermission('animal_update');
        $userHotelId = get_user_hotel_id();
        $animal = $this->animalClass::find($id);

        if (!$animal) {
            return redirect()->back()->with('error', __('Not Found'));
        }
        $animal->hotels()->detach($userHotelId);
        return redirect()->back()->with('success', __('Detach success!'));
    }

    public function delete($id)
    {
        $this->checkPermission('animal_delete');
        $user_id = Auth::id();
        if(\request()->query('permanently_delete')){
            $query = $this->animalClass::where("author_id", $user_id)->where("id", $id)->withTrashed()->first();
            if (!empty($query)) {
                $query->forceDelete();
            }
        }else {
            $query = $this->animalClass::where("author_id", $user_id)->where("id", $id)->first();
            if (!empty($query)) {
                $query->delete();
                event(new UpdatedServiceEvent($query));
            }
        }
        return redirect(route('animal.vendor.index'))->with('success', __('Delete animal success!'));
    }

    public function bookingReportBulkEdit($booking_id , Request $request){
        $status = $request->input('status');
        if (!empty(setting_item("car_allow_vendor_can_change_their_booking_status")) and !empty($status) and !empty($booking_id)) {
            $query = $this->bookingClass::where("id", $booking_id);
            $query->where("vendor_id", Auth::id());
            $item = $query->first();
            if(!empty($item)){
                $item->status = $status;
                $item->save();

                if($status == Booking::CANCELLED) $item->tryRefundToWallet();
                event(new BookingUpdatedEvent($item));
                return redirect()->back()->with('success', __('Update success'));
            }
            return redirect()->back()->with('error', __('Booking not found!'));
        }
        return redirect()->back()->with('error', __('Update fail!'));
    }
}
