<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 7/30/2019
 * Time: 1:56 PM
 */
namespace Modules\Weapon\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Modules\AdminController;
use Modules\Animals\Hook;
use Modules\Core\Events\CreatedServicesEvent;
use Modules\Core\Events\UpdatedServiceEvent;
use Modules\Core\Models\Attributes;
use Modules\Location\Models\Location;
use Modules\Weapon\Models\Caliber;
use Modules\Weapon\Models\CaliberTranslation;

class CaliberController extends AdminController
{
    protected $caliber;
    protected $location;
    protected $caliberTranslation;
    protected $indexView = 'Weapon::frontend.user.availability';

    public function __construct(Caliber $caliber,CaliberTranslation $caliberTranslation,Location $location)
    {

        $this->setActiveMenu(route('caliber.admin.index'));
        $this->caliber = $caliber;
        $this->caliberTranslation = $caliberTranslation;
        $this->location = $location;
    }

    public function callAction($method, $parameters)
    {
        if (!Caliber::isEnable()) {
            return redirect('/');
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }
    public function index(Request $request)
    {
        $this->checkPermission('caliber_view');
        $query = $this->caliber::query();
        $query->orderBy('id', 'desc');

//        if (!empty($s = $request->input('s'))) {
//            $query->where('title', 'LIKE', '%' . $s . '%');
//            $query->orderBy('title', 'asc');
//        }
//        if (!empty($location_id = $request->query('location_id'))) {
//            $query->where('location_id', $location_id);
//        }
//        if ($this->hasPermission('animal_manage_others')) {
//            if (!empty($author = $request->input('vendor_id'))) {
//                $query->where('author_id', $author);
//            }
//        } else {
//            $query->where('author_id', Auth::id());
//        }
        $data = [
            'rows' => $query->paginate(20),
            'animal_manage_others' => $this->hasPermission('animal_manage_others'),
            'breadcrumbs' => [
                [
                    'name' => __('Caliber'),
                    'url' => route('caliber.admin.index')
                ],
                [
                    'name' => __('All'),
                    'class' => 'active'
                ],
            ],
            'page_title' => __("Caliber Management")
        ];

        return view('Weapon::admin.caliber.caliber', $data);
//        return view($this->indexView, $data);
    }

    public function create(Request $request)
    {
//        $this->checkPermission('animal_create');
        $row = new $this->caliber();
        $row->fill([
            'status' => 'publish'
        ]);
        $data = [
            'row'          => $row,
//            'attributes'   => $this->attributes::where('service', 'weapon')->get(),
            'attributes'   => '',
//            'caliber_location' => $this->location::where('status', 'publish')->get()->toTree(),
            'translation' => new CaliberTranslation(),
            'breadcrumbs'  => [
                [
                    'name' => __('Caliber'),
                    'url'  => route('caliber.admin.index')
                ],
                [
                    'name'  => __('Add new caliber'),
                    'class' => 'active'
                ],
            ],
            'page_title'   => __("Add new caliber")
        ];
        return view('Weapon::admin.caliber.detail', $data);
    }

    public function store(Request $request, $id)
    {
        if(is_demo_mode()){
            return redirect()->back()->with('danger',__("DEMO MODE: can not add data"));
        }

        if ($id > 0) {

//            $this->checkPermission('animal_update');
            $row = $this->caliber::find($id);

            if (empty($row)) {
                return redirect(route('caliber.admin.index'));
            }
            if ($row->author_id != Auth::id() and !$this->hasPermission('animal_manage_others')) {
                return redirect(route('caliber.admin.index'));
            }
        } else {
//            $this->checkPermission('animal_create');
            $row = new $this->caliber();
            $row->status = "publish";
        }
        $dataKeys = [
            'title',
            'content',
            'status',
            'video',
            'faqs',
            'image_id',
            'banner_image_id',
            'gallery',
            'location_id',
            'address',
            'map_lat',
            'map_lng',
            'map_zoom',
            'number',
            'is_featured',
            'default_state',
            'ical_import_url'
        ];
//        if ($this->hasPermission('animal_manage_others')) {
//            $dataKeys[] = 'author_id';
//        }
        $row->fillByAttr($dataKeys, $request->input());
        if ($request->input('slug')) {
            $row->slug = $request->input('slug');
        }

        $res = $row->saveOriginOrTranslation($request->input('lang'), true);


        if ($res) {
            if (!$request->input('lang') or is_default_lang($request->input('lang'))) {
//                $this->saveTerms($row, $request);
            }
//            do_action(Hook::AFTER_SAVING,$row,$request);

            if ($id > 0) {
//                event(new UpdatedServiceEvent($row));
                return back()->with('success', __('Weapon updated'));
            } else {
//                event(new CreatedServicesEvent($row));
                return redirect(route('caliber.admin.edit', 2))->with('success', __('Weapon created'));
            }
        }
    }

    public function edit(Request $request, $id)
    {
//        $this->checkPermission('animal_update');
        $row = $this->caliber::find($id);
        if (empty($row)) {
            return redirect(route('caliber.admin.index'));
        }
        $translation = $row->translate($request->query('lang',get_main_lang()));
        if (!$this->hasPermission('caliber')) {
            if ($row->author_id != Auth::id()) {
                return redirect(route('caliber.admin.index'));
            }
        }
        $data = [
            'row'               => $row,
            'translation'       => $translation,
//            "selected_terms"    => $row->terms->pluck('term_id'),
//            'attributes'        => $this->attributes::where('service', 'weapon')->get(),
            'weapon_location'      => $this->location::where('status', 'publish')->get()->toTree(),
            'enable_multi_lang' => true,
            'breadcrumbs'       => [
                [
                    'name' => __('Animal'),
                    'url'  => route('caliber.admin.index')
                ],
                [
                    'name'  => __('Edit Animal'),
                    'class' => 'active'
                ],
            ],
            'page_title'        => __("Edit: :name", ['name' => $row->title])
        ];
        return view('Weapon::admin.caliber.detail', $data);
    }

    public function bulkEdit(Request $request)
    {

        $ids = $request->input('ids');
        $action = $request->input('action');
        if (empty($ids) or !is_array($ids)) {
            return redirect()->back()->with('error', __('No items selected!'));
        }
        if (empty($action)) {
            return redirect()->back()->with('error', __('Please select an action!'));
        }
        switch ($action) {
            case "delete":
                foreach ($ids as $id) {
                    $query = $this->caliber::where("id", $id);
                    if (!$this->hasPermission('animal_manage_others')) {
                        $query->where("create_user", Auth::id());
                        $this->checkPermission('animal_delete');
                    }
                    $row = $query->first();
                    if (!empty($row)) {
                        $row->delete();
                        event(new UpdatedServiceEvent($row));
                    }
                }
                return redirect()->back()->with('success', __('Deleted success!'));
                break;
            case "permanently_delete":
                foreach ($ids as $id) {
                    $query = $this->caliber::where("id", $id);
                    if (!$this->hasPermission('animal_manage_others')) {
                        $query->where("create_user", Auth::id());
                        $this->checkPermission('animal_delete');
                    }
                    $row = $query->withTrashed()->first();
                    if ($row) {
                        $row->forceDelete();
                    }
                }
                return redirect()->back()->with('success', __('Permanently delete success!'));
                break;
            case "recovery":
                foreach ($ids as $id) {
                    $query = $this->caliber::withTrashed()->where("id", $id);
                    if (!$this->hasPermission('animal_manage_others')) {
                        $query->where("create_user", Auth::id());
                        $this->checkPermission('animal_delete');
                    }
                    $row = $query->first();
                    if (!empty($row)) {
                        $row->restore();
                        event(new UpdatedServiceEvent($row));
                    }
                }
                return redirect()->back()->with('success', __('Recovery success!'));
                break;
            case "clone":
                $this->checkPermission('animal_create');
                foreach ($ids as $id) {
                    (new $this->caliber())->saveCloneByID($id);
                }
                return redirect()->back()->with('success', __('Clone success!'));
                break;
            default:
                // Change status
                foreach ($ids as $id) {
                    $query = $this->caliber::where("id", $id);
                    if (!$this->hasPermission('animal_manage_others')) {
                        $query->where("create_user", Auth::id());
                        $this->checkPermission('animal_update');
                    }
                    $row = $query->first();
                    $row->status = $action;
                    $row->save();
                    event(new UpdatedServiceEvent($row));
                }
                return redirect()->back()->with('success', __('Update success!'));
                break;
        }
    }
}
