<?php
namespace Modules\Animals\User;

use App\Http\Responses\SuccessResponse;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Modules\Animals\DTO\AnimalPricePeriodUpdateDTO;
use Modules\Animals\Models\Animal;
use Modules\Animals\Models\AnimalDate;
use Modules\Animals\Models\AnimalPricePeriod;
use Modules\Animals\Requests\UpdateAnimalPricePeriodRequest;
use Modules\Animals\Services\OrganisationService;
use Modules\Booking\Models\Booking;
use Modules\FrontendController;

class OrganisationController extends FrontendController
{
    protected $animalClass;
    protected $animalDateClass;
    protected $bookingClass;


    protected string $indexView = 'Animals::user.organisation';

    public function __construct(Animal $animalClass, AnimalDate $animalDateClass, Booking $bookingClass, private readonly OrganisationService $organisationService)
    {
        parent::__construct();
        $this->setActiveMenu(route('animal.vendor.organisation'));
        $this->animalClass = $animalClass;
        $this->animalDateClass = $animalDateClass;
        $this->bookingClass = $bookingClass;
    }

    public function callAction($method, $parameters)
    {
        if(!Animal::isEnable())
        {
            return redirect('/');
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }

    public function index(Request $request){
        $this->checkPermission('animal_create_hunting');
        $userHotelId = get_user_hotel_id();

        $list_animals = $this->animalClass::query()
            ->join('bc_hotel_animals as bha', function ($join) use ($userHotelId) {
                $join->on('bha.animal_id', '=', 'bc_animals.id')
                    ->where('bha.hotel_id', '=', $userHotelId);
            })
            ->select([
                'bc_animals.*',
                'bha.status as animal_status'
            ]);

        if($request->query('s')){
            $list_animals->where('title','like','%'.$request->query('s').'%');
        }

        if($request->query('s')){
            $list_animals->where('bc_animals.title', 'like', '%'.$request->query('s').'%');
        }

        $list_animals->orderBy('bc_animals.id', 'desc');
        $rows = $list_animals->paginate(15);

        $current_month = strtotime(date('Y-m-01',time()));

        if($request->query('month')){
            $date = date_create_from_format('m-Y',$request->query('month'));
            if(!$date){
                $current_month = time();
            }else{
                $current_month = $date->getTimestamp();
            }
        }
        $breadcrumbs = [
            [
                'name' => __('Animal'),
                'url'  => route('animal.vendor.index')
            ],
            [
                'name'  => __('Hunting organization'),
                'class' => 'active'
            ],
        ];
        $page_title = __('Hunting organization');

        return view($this->indexView, compact('rows','breadcrumbs','current_month','page_title','request'));
    }
    public function create($animalId): JsonResponse
    {
        $result = $this->organisationService->createPeriod($animalId);

        $result['data']['html'] = view('Animal::frontend.partials.period_row', ['period' => $result['data']['period']])->render();

        return new SuccessResponse(code: $result['code'], domain: 'animal', data: $result['data']);
    }

    public function update(UpdateAnimalPricePeriodRequest $request, AnimalPricePeriod $period): JsonResponse
    {
        $data = AnimalPricePeriodUpdateDTO::fromRequest($request);
        $result = $this->organisationService->updatePeriod($period, $data);

        return new SuccessResponse(code: $result['code'], domain: 'animal');
    }

    public function delete(AnimalPricePeriod $period): JsonResponse
    {
        $result = $this->organisationService->deletePeriod($period);

        return new SuccessResponse(code: $result['code'], domain: 'animal', data: $result['data']);
    }
}
