<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 7/30/2019
 * Time: 1:56 PM
 */
namespace Modules\Animals\Admin;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Modules\AdminController;
use Modules\Animals\Hook;
use Modules\Animals\Models\Animal;
use Modules\Animals\Models\AnimalFine;
use Modules\Animals\Models\AnimalPreparation;
use Modules\Animals\Models\AnimalTranslation;
use Modules\Animals\Models\AnimalTrophy;
use Modules\Core\Events\CreatedServicesEvent;
use Illuminate\Support\Facades\Log;
use Modules\Core\Events\UpdatedServiceEvent;
use Modules\Core\Models\Attributes;
use Modules\Location\Models\Location;

class AnimalController extends AdminController
{
    protected $animal;
    protected $animal_translation;
    protected $attributes;
    protected $location;

    public function __construct(Animal $animal,AnimalTranslation $animal_translation,Attributes $attributes, Location $location)
    {

        $this->setActiveMenu(route('animal.admin.index'));
        $this->animal = $animal;
        $this->animal_translation = $animal_translation;
        $this->attributes = $attributes;
        $this->location = $location;
    }

    public function callAction($method, $parameters)
    {
        if (!Animal::isEnable()) {
            return redirect('/');
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }

    public function index(Request $request)
    {
        $this->checkPermission('animal_view');
        $query = $this->animal::query();
        $query->orderBy('id', 'desc');

        if (!empty($s = $request->input('s'))) {
            $query->where('title', 'LIKE', '%' . $s . '%');
            $query->orderBy('title', 'asc');
        }
        if (!empty($location_id = $request->query('location_id'))) {
            $query->where('location_id', $location_id);
        }
        if ($this->hasPermission('animal_manage_others')) {
            if (!empty($author = $request->input('vendor_id'))) {
                $query->where('author_id', $author);
            }
        } else {
            $query->where('author_id', Auth::id());
        }
        $data = [
            'rows'              => $query->with(['author'])->paginate(20),
            'animal_manage_others' => $this->hasPermission('animal_manage_others'),
            'breadcrumbs'       => [
                [
                    'name' => __('Animals'),
                    'url'  => route('animal.admin.index')
                ],
                [
                    'name'  => __('All'),
                    'class' => 'active'
                ],
            ],
            'page_title'        => __("Animal Management")
        ];

        return view('Animals::admin.index', $data);
    }

    public function recovery(Request $request)
    {
        $this->checkPermission('animal_view');
        $query = $this->animal::onlyTrashed();
        $query->orderBy('id', 'desc');
        if (!empty($s = $request->input('s'))) {
            $query->where('title', 'LIKE', '%' . $s . '%');
            $query->orderBy('title', 'asc');
        }
        if ($this->hasPermission('animal__manage_others')) {
            if (!empty($author = $request->input('vendor_id'))) {
                $query->where('author_id', $author);
            }
        } else {
            $query->where('author_id', Auth::id());
        }
        $data = [
            'rows'              => $query->with(['author'])->paginate(20),
            'animal_manage_others' => $this->hasPermission('animal__manage_others'),
            'recovery'          => 1,
            'breadcrumbs'       => [
                [
                    'name' => __('Animals'),
                    'url'  => route('animal.admin.index')
                ],
                [
                    'name'  => __('Recovery'),
                    'class' => 'active'
                ],
            ],
            'page_title'        => __("Recovery Animals Management")
        ];
        return view('Animals::admin.index', $data);
    }

    public function create(Request $request)
    {
        $this->checkPermission('animal_create');
        $row = new $this->animal();
        $row->fill([
            'status' => 'publish'
        ]);
        $data = [
            'row'          => $row,
            'attributes'   => $this->attributes::where('service', 'animal')->get(),
            'car_location' => $this->location::where('status', 'publish')->get()->toTree(),
            'translation'  => new $this->animal_translation(),
            'trophies'     => collect([]),
            'breadcrumbs'  => [
                [
                    'name' => __('Animals'),
                    'url'  => route('animal.admin.index')
                ],
                [
                    'name'  => __('Add Animal'),
                    'class' => 'active'
                ],
            ],
            'page_title'   => __("Add new Animal")
        ];
        return view('Animals::admin.detail', $data);
    }

    public function edit(Request $request, $id)
    {
        $this->checkPermission('animal_update');
        $row = $this->animal::find($id);
        if (empty($row)) {
            return redirect(route('animal.admin.index'));
        }
        $translation = $row->translate($request->query('lang',get_main_lang()));
        if (!$this->hasPermission('animal_manage_others')) {
            if ($row->author_id != Auth::id()) {
                return redirect(route('animal.admin.index'));
            }
        }
        $data = [
            'row'               => $row,
            'translation'       => $translation,
//            "selected_terms"    => $row->terms->pluck('term_id'),
            'attributes'        => $this->attributes::where('service', 'animal')->get(),
            'animal_location'      => $this->location::where('status', 'publish')->get()->toTree(),
            'enable_multi_lang' => true,
            'trophies'          => $row->trophies,
            'fines'             => $row->fines,
            'preparations'             => $row->preparations,
            'breadcrumbs'       => [
                [
                    'name' => __('Animal'),
                    'url'  => route('animal.admin.index')
                ],
                [
                    'name'  => __('Edit Animal'),
                    'class' => 'active'
                ],
            ],
            'page_title'        => __("Edit: :name", ['name' => $row->title])
        ];
        return view('Animals::admin.detail', $data);
    }

    public function store(Request $request, $id)
    {
        if(is_demo_mode()){
            return redirect()->back()->with('danger',__("DEMO MODE: can not add data"));
        }

        if ($id > 0) {

            $this->checkPermission('animal_update');
            $row = $this->animal::find($id);

            if (empty($row)) {
                return redirect(route('animal.admin.index'));
            }
            if ($row->author_id != Auth::id() and !$this->hasPermission('animal_manage_others')) {
                return redirect(route('animal.admin.index'));
            }
        } else {
            $this->checkPermission('animal_create');
            $row = new $this->animal();
            $row->status = "publish";
            // Устанавливаем автора по умолчанию, если нет разрешения на управление другими
            if (!$this->hasPermission('animal_manage_others')) {
                $row->author_id = Auth::id();
            }
        }
        $dataKeys = [
            'title',
            'content',
            'price',
            'is_instant',
            'status',
            'video',
            'faqs',
            'image_id',
            'banner_image_id',
            'gallery',
            'location_id',
            'address',
            'map_lat',
            'map_lng',
            'map_zoom',
            'number',
            'is_featured',
            'default_state',
            'enable_service_fee',
            'ical_import_url'
        ];
        if ($this->hasPermission('animal_manage_others')) {
            $dataKeys[] = 'author_id';
        }
        $row->fillByAttr($dataKeys, $request->input());
        if ($request->input('slug')) {
            $row->slug = $request->input('slug');
        }

        $res = $row->saveOriginOrTranslation($request->input('lang'), true);

        if ($res) {
            // Обновляем объект после сохранения, чтобы получить актуальный ID
            $row->refresh();

            if (!$request->input('lang') or is_default_lang($request->input('lang'))) {
//                $this->saveTerms($row, $request);
                // Сохраняем трофеи только если у животного есть ID
                if ($row->id) {
                    try {
                        $this->saveTrophies($row, $request);
                        $this->saveFines($row, $request);
                        $this->savePreparations($row, $request);
                    } catch (\Exception $e) {
                        \Log::error('Error saving trophies: ' . $e->getMessage());
                    }
                }
            }
            do_action(Hook::AFTER_SAVING,$row,$request);

            if ($id > 0) {
                event(new UpdatedServiceEvent($row));
                return back()->with('success', __('Animal updated'));
            } else {
                event(new CreatedServicesEvent($row));
                return redirect(route('animal.admin.edit', ['id' => $row->id]))->with('success', __('Animal created'));
            }
        }

        return back()->with('error', __('Error saving animal. Please check the data and try again.'));
    }

//    public function saveTerms($row, $request)
//    {
//        $this->checkPermission('car_manage_attributes');
//        if (empty($request->input('terms'))) {
//            $this->car_term::where('target_id', $row->id)->delete();
//        } else {
//            $term_ids = $request->input('terms');
//            foreach ($term_ids as $term_id) {
//                $this->car_term::firstOrCreate([
//                    'term_id'   => $term_id,
//                    'target_id' => $row->id
//                ]);
//            }
//            $this->car_term::where('target_id', $row->id)->whereNotIn('term_id', $term_ids)->delete();
//        }
//    }

    public function saveTrophies($row, $request)
    {
        if (!$row || !$row->id) {
            return;
        }

        $trophy_types = $request->input('trophy_types', []);

        if (empty($trophy_types) || !is_array($trophy_types)) {
            try {
                AnimalTrophy::where('animal_id', $row->id)->delete();
            } catch (\Exception $e) {
                \Log::error('Error deleting trophies: ' . $e->getMessage());
            }
            return;
        }

        try {
            $existingTrophies = AnimalTrophy::where('animal_id', $row->id)->get()->keyBy('id');
            $keepIds = [];

            foreach ($trophy_types as $trophy_data) {
                if (!is_array($trophy_data)) continue;

                $type = trim($trophy_data['type'] ?? '');

                $trophy_id = !empty($trophy_data['id']) ? (int)$trophy_data['id'] : null;

                if (!empty($type)) {
                    if ($trophy_id && $existingTrophies->has($trophy_id)) {
                        $existingTrophy = $existingTrophies->get($trophy_id);
                        AnimalTrophy::where('id', $trophy_id)
                            ->where('animal_id', $row->id)
                            ->update([
                                'type' => $type,
                                'price' => $existingTrophy->price,
                            ]);
                        $keepIds[] = $trophy_id;
                    } else {
                        $newTrophy = AnimalTrophy::create([
                            'animal_id' => $row->id,
                            'type' => $type,
                            'price' => null,
                        ]);
                        $keepIds[] = $newTrophy->id;
                    }
                }
            }
            if (!empty($keepIds)) {
                AnimalTrophy::where('animal_id', $row->id)
                    ->whereNotIn('id', $keepIds)
                    ->delete();
            } else {
                AnimalTrophy::where('animal_id', $row->id)->delete();
            }
        } catch (\Exception $e) {
            \Log::error('Error saving trophies for animal ' . $row->id . ': ' . $e->getMessage());
        }
    }

    public function saveFines($row, $request): void
    {
        if (!$row || !$row->id) {
            return;
        }

        $fine_types = $request->input('fines_types', []);

        if (empty($fine_types) || !is_array($fine_types)) {
            try {
                AnimalFine::where('animal_id', $row->id)->delete();
            } catch (\Exception $e) {
                \Log::error('Error deleting trophies: ' . $e->getMessage());
            }
            return;
        }

        try {
            $existingTrophies = AnimalFine::where('animal_id', $row->id)->get()->keyBy('id');
            $keepIds = [];

            foreach ($fine_types as $fine_data) {
                if (!is_array($fine_data)) continue;

                $type = trim($fine_data['type'] ?? '');
                $fine_id = !empty($fine_data['id']) ? (int)$fine_data['id'] : null;

                if (!empty($type)) {
                    if ($fine_id && $existingTrophies->has($fine_id)) {
                        $existingTrophy = $existingTrophies->get($fine_id);
                        AnimalFine::where('id', $fine_id)
                            ->where('animal_id', $row->id)
                            ->update([
                                'type' => $type,
                                'price' => $existingTrophy->price,
                            ]);
                        $keepIds[] = $fine_id;
                    } else {
                        $newTrophy = AnimalFine::create([
                            'animal_id' => $row->id,
                            'type' => $type,
                            'price' => null,
                        ]);
                        $keepIds[] = $newTrophy->id;
                    }
                }
            }

            if (!empty($keepIds)) {
                AnimalFine::where('animal_id', $row->id)
                    ->whereNotIn('id', $keepIds)
                    ->delete();
            } else {
                AnimalFine::where('animal_id', $row->id)->delete();
            }
        } catch (\Exception $e) {
            \Log::error('Error saving trophies for animal ' . $row->id . ': ' . $e->getMessage());
        }
    }

    public function savePreparations($row, $request): void
    {
        if (!$row || !$row->id) {
            return;
        }

        $preparation_types = $request->input('preparation_types', []);

        if (empty($preparation_types) || !is_array($preparation_types)) {
            try {
                AnimalPreparation::where('animal_id', $row->id)->delete();
            } catch (\Exception $e) {
                \Log::error('Error deleting trophies: ' . $e->getMessage());
            }
            return;
        }

        try {
            $existingTrophies = AnimalPreparation::where('animal_id', $row->id)->get()->keyBy('id');
            $keepIds = [];

            foreach ($preparation_types as $fine_data) {
                if (!is_array($fine_data)) continue;

                $type = trim($fine_data['type'] ?? '');
                $fine_id = !empty($fine_data['id']) ? (int)$fine_data['id'] : null;

                if (!empty($type)) {
                    if ($fine_id && $existingTrophies->has($fine_id)) {
                        $existingTrophy = $existingTrophies->get($fine_id);
                        AnimalPreparation::where('id', $fine_id)
                            ->where('animal_id', $row->id)
                            ->update([
                                'type' => $type,
                                'price' => $existingTrophy->price,
                            ]);
                        $keepIds[] = $fine_id;
                    } else {
                        $newTrophy = AnimalPreparation::create([
                            'animal_id' => $row->id,
                            'type' => $type,
                            'price' => null,
                        ]);
                        $keepIds[] = $newTrophy->id;
                    }
                }
            }

            if (!empty($keepIds)) {
                AnimalPreparation::where('animal_id', $row->id)
                    ->whereNotIn('id', $keepIds)
                    ->delete();
            } else {
                AnimalPreparation::where('animal_id', $row->id)->delete();
            }
        } catch (\Exception $e) {
            \Log::error('Error saving trophies for animal ' . $row->id . ': ' . $e->getMessage());
        }
    }

    public function bulkEdit(Request $request)
    {

        $ids = $request->input('ids');
        $action = $request->input('action');
        if (empty($ids) or !is_array($ids)) {
            return redirect()->back()->with('error', __('No items selected!'));
        }
        if (empty($action)) {
            return redirect()->back()->with('error', __('Please select an action!'));
        }
        switch ($action) {
            case "delete":
                foreach ($ids as $id) {
                    $query = $this->animal::where("id", $id);
                    if (!$this->hasPermission('animal_manage_others')) {
                        $query->where("create_user", Auth::id());
                        $this->checkPermission('animal_delete');
                    }
                    $row = $query->first();
                    if (!empty($row)) {
                        $row->delete();
                        event(new UpdatedServiceEvent($row));
                    }
                }
                return redirect()->back()->with('success', __('Deleted success!'));
                break;
            case "permanently_delete":
                foreach ($ids as $id) {
                    $query = $this->animal::where("id", $id);
                    if (!$this->hasPermission('animal_manage_others')) {
                        $query->where("create_user", Auth::id());
                        $this->checkPermission('animal_delete');
                    }
                    $row = $query->withTrashed()->first();
                    if ($row) {
                        $row->forceDelete();
                    }
                }
                return redirect()->back()->with('success', __('Permanently delete success!'));
                break;
            case "recovery":
                foreach ($ids as $id) {
                    $query = $this->animal::withTrashed()->where("id", $id);
                    if (!$this->hasPermission('animal_manage_others')) {
                        $query->where("create_user", Auth::id());
                        $this->checkPermission('animal_delete');
                    }
                    $row = $query->first();
                    if (!empty($row)) {
                        $row->restore();
                        event(new UpdatedServiceEvent($row));
                    }
                }
                return redirect()->back()->with('success', __('Recovery success!'));
                break;
            case "clone":
                $this->checkPermission('animal_create');
                foreach ($ids as $id) {
                    (new $this->animal())->saveCloneByID($id);
                }
                return redirect()->back()->with('success', __('Clone success!'));
                break;
            default:
                // Change status
                foreach ($ids as $id) {
                    $query = $this->animal::where("id", $id);
                    if (!$this->hasPermission('animal_manage_others')) {
                        $query->where("create_user", Auth::id());
                        $this->checkPermission('animal_update');
                    }
                    $row = $query->first();
                    $row->status = $action;
                    $row->save();
                    event(new UpdatedServiceEvent($row));
                }
                return redirect()->back()->with('success', __('Update success!'));
                break;
        }
    }

//    public function getForSelect2(Request $request)
//    {
//        $pre_selected = $request->query('pre_selected');
//        $selected = $request->query('selected');
//        if ($pre_selected && $selected) {
//            if (is_array($selected)) {
//                $items = $this->car::select('id', 'title as text')->whereIn('id', $selected)->take(50)->get();
//            } else {
//                $items = $this->car::find($selected);
//            }
//            return [
//                'results'=>$items
//            ];
//        }
//        $q = $request->query('q');
//        $query = $this->car::select('id', 'title as text')->where("status", "publish");
//        if ($q) {
//            $query->where('title', 'like', '%' . $q . '%');
//        }
//        $res = $query->orderBy('id', 'desc')->limit(20)->get();
//        return $this->sendSuccess([
//            'results' => $res
//        ]);
//    }
}
