<?php
namespace Modules\Animals\Controllers;

use Carbon\Carbon;
use ICal\ICal;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;
use Modules\Animals\Models\Animal;
use Modules\Animals\Models\AnimalDate;
use Modules\Animals\Models\AnimalPricePeriod;
use Modules\Booking\Models\Booking;
use Modules\FrontendController;
use Modules\Hotel\Models\Hotel;

class AvailabilityController extends FrontendController{

    protected $animalClass;
    /**
     * @var AnimalDate
     */
    protected $animalDateClass;

    /**
     * @var Booking
     */
    protected $bookingClass;

    protected $indexView = 'Animal::frontend.user.availability';

    public function __construct(Animal $animalClass, AnimalDate  $animalDateClass, Booking $bookingClass)
    {
        parent::__construct();
        $this->animalClass = $animalClass;
        $this->animalDateClass = $animalDateClass;
        $this->bookingClass = $bookingClass;
    }

    public function callAction($method, $parameters)
    {
        if(!Animal::isEnable())
        {
            return redirect('/');
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }
    public function index(Request $request){
        $this->checkPermission('animal_create');

        $q = $this->animalClass::query();

        if($request->query('s')){
            $q->where('title','like','%'.$request->query('s').'%');
        }

        $rows = $q->paginate(15);

        $current_month = strtotime(date('Y-m-01',time()));

        if($request->query('month')){
            $date = date_create_from_format('m-Y',$request->query('month'));
            if(!$date){
                $current_month = time();
            }else{
                $current_month = $date->getTimestamp();
            }
        }
        $breadcrumbs = [
            [
                'name' => __('Animals'),
                'url'  => route('animal.vendor.index')
            ],
            [
                'name'  => __('Availability'),
                'class' => 'active'
            ],
        ];
        $page_title = __('Animal Availability');

        return view($this->indexView,compact('rows','breadcrumbs','current_month','page_title','request'));
    }

    public function loadDates(Request $request)
    {
        $rules = [
            'id' => 'required',
            'start' => 'required',
            'end' => 'required',
        ];
        $validator = Validator::make($request->all(), $rules);
        if ($validator->fails()) {
            return $this->sendError($validator->errors());
        }

        $animal = $this->animalClass::find($request->query('id'));
        if (!$animal) {
            return $this->sendError(__('Animal not found'));
        }

        $calendarStart = Carbon::parse($request->start)->startOfDay();
        $calendarEnd   = Carbon::parse($request->end)->endOfDay();

        $rows = $this->animalDateClass::query()
            ->where('target_id', $animal->id)
            ->where('end_date', '>=', $calendarStart)
            ->where('start_date', '<=', $calendarEnd)
            ->get();

        $events = [];

        foreach ($rows as $row) {
            $rowStart = Carbon::parse($row->start_date)->startOfDay();
            $rowEnd   = Carbon::parse($row->end_date)->startOfDay();

            $excludedDates = $row->excluded_dates ? json_decode($row->excluded_dates, true) : [];

            for ($date = $rowStart; $date->lte($rowEnd); $date->addDay()) {
                $dateStr = $date->format('Y-m-d');

                if (in_array($dateStr, $excludedDates)) {
                    continue;
                }

                $event = [
                    'id' => $row->id . '-' . $date->format('Ymd'),
                    'start' => $dateStr,
                    'allDay' => true,
                ];

                if ($row->active) {
                    $event['title'] = 'Доступно';
                    $event['classNames'] = ['available-event'];
                }

                $events[] = $event;
            }
        }

        return response()->json($events);
    }

    public function store(Request $request)
    {
        $request->validate([
            'target_id'=>'required',
            'start_date'=>'required',
            'end_date'=>'required',
        ]);
        $target_id = $request->input('target_id');
        $type = $request->input('type', null);

        $animal = $this->animalClass::find($target_id);


        if(empty($animal)){
            return $this->sendError(__('Animal not found'));
        }

        if ($type === 'range') {
            $date = $this->animalDateClass::firstOrNew([
                'target_id' => $target_id,
            ]);

            $date->active = $animal->status === 'publish';
            $date->start_date = $request->input('start_date');
            $date->end_date = $request->input('end_date');
            $date->excluded_dates = json_encode([]);
            $date->save();
        }
        return $this->sendSuccess([],__("Update Success"));

    }

    public function checkAvailability(): \Illuminate\Http\JsonResponse
    {
        $animal_id = \request('animal_id');
        $hotel_id = \request('hotel_id');
        $start_date = request('start_date');
        $adults = request('adults');
        $start_date_hotel = request('start_date_hotel');
        $end_date_hotel = request('end_date_hotel');

        if(\request()->input('firstLoad') == "false") {
            $rules = [
                'hotel_id'   => 'required',
                'start_date' => 'required:date_format:Y-m-d',
                'adults'     => 'required',
                'animal_id'     => 'required',
            ];
            $validator = \Validator::make(request()->all(), $rules);
            if ($validator->fails()) {
                return $this->sendError($validator->errors()->all());
            }

            if(empty($start_date)){
                return $this->sendError(__("Please select a date"));
            }
        }

        // ДОПОЛНИТЕЛЬНАЯ ПРОВЕРКА: если выбраны даты проживания, проверяем диапазон
        // Если выбрано только животное (без номера) - проверку не делаем
        if ($start_date_hotel && $end_date_hotel) {
            $stayStart = Carbon::parse($start_date_hotel)->startOfDay();
            $stayEnd = Carbon::parse($end_date_hotel)->startOfDay();
            $huntDate = Carbon::parse($start_date)->startOfDay();

            // Дата охоты должна быть > даты заезда И <= даты выезда
            if ($huntDate->lte($stayStart) || $huntDate->gt($stayEnd)) {
                return $this->sendError('Дата охоты должна быть в пределах дат проживания');
            }
        }

        $range = AnimalDate::getDatesInRanges($start_date, $start_date, $animal_id)->first();

        if (!$range || ( $range->excluded_dates && in_array($start_date, json_decode($range->excluded_dates, true)) )) {
            return $this->sendError('На эту дату охота на это животное недоступна');
        }

        $period = AnimalPricePeriod::query()
            ->where('animal_id', $animal_id)
            ->whereDate('start_date', '<=', $start_date)
            ->whereDate('end_date', '>=', $start_date)
            ->first();

        if (!$period) {
            return $this->sendError('На выбранную дату нет ценового периода');
        }

        // Проверка минимального количества охотников
        if ($adults && $hotel_id && $animal_id) {
            $minHuntersCount = DB::table('bc_hotel_animals')
                ->where('hotel_id', $hotel_id)
                ->where('animal_id', $animal_id)
                ->value('hunters_count');

            // Если минимальное количество установлено и выбрано меньше охотников
            if ($minHuntersCount && (int)$adults < (int)$minHuntersCount) {
                return $this->sendError("Минимальное количество охотников для этого животного: {$minHuntersCount}. Вы выбрали: {$adults}");
            }
        }

        $animalBookedCount = Booking::where('object_model', 'animal')
            ->whereDate('start_date', '=', $start_date)
            ->where('hotel_id', $hotel_id)
            ->where('status', 'processing')
            ->count();

        $hotel = Hotel::find($hotel_id);
        $maxTotalHunts = (int) $hotel->max_hunts_per_day;

//        if ($animalBookedCount + 1 > $maxTotalHunts) {
//            return $this->sendError('На эту дату лимит охот на выбранное животное исчерпан');
//        }
        return $this->sendSuccess(['available' => true, 'price' => $period->price]);
    }
}
