<?php
namespace Modules\Animals\Controllers;

use Carbon\Carbon;
use ICal\ICal;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;
use Modules\Animals\Models\Animal;
use Modules\Animals\Models\AnimalPricePeriod;
use Modules\FrontendController;
use Modules\Hotel\Models\Hotel;

class HuntingController extends FrontendController{

    protected $animalClass;
    /**
     * @var AnimalPricePeriod
     */
    protected $animalPricePeriod;

    protected $indexView = 'Animal::frontend.user.hunting';

    public function __construct(Animal $animalClass, AnimalPricePeriod $animalPricePeriod)
    {
        parent::__construct();
        $this->animalClass = $animalClass;
        $this->animalPricePeriod = $animalPricePeriod;
    }

    public function callAction($method, $parameters)
    {
        if(!Animal::isEnable())
        {
            return redirect('/');
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }
    public function index(Request $request){
        $this->checkPermission('animal_create_hunting');

        $q = $this->animalClass::query();

        if($request->query('s')){
            $q->where('title','like','%'.$request->query('s').'%');
        }

        if(!$this->hasPermission('animal_manage_others')){
            $q->where('author_id',$this->currentUser()->id);
        }

        $userHotelId = get_user_hotel_id();
        if ($userHotelId) {
            $q->where('hotel_id', $userHotelId);
        }

        $q->orderBy('bc_animals.id','desc');

        $rows = $q->paginate(15);

        $current_month = strtotime(date('Y-m-01',time()));

        if($request->query('month')){
            $date = date_create_from_format('m-Y',$request->query('month'));
            if(!$date){
                $current_month = time();
            }else{
                $current_month = $date->getTimestamp();
            }
        }
        $breadcrumbs = [
            [
                'name' => __('Animal'),
                'url'  => route('animal.vendor.index')
            ],
            [
                'name'  => __('Hunting organization'),
                'class' => 'active'
            ],
        ];
        $page_title = __('Hunting organization');

        return view($this->indexView,compact('rows','breadcrumbs','current_month','page_title','request'));
    }

    public function loadDates(Request $request)
    {
        $rules = [
            'id' => 'required',
            'start' => 'required',
            'end' => 'required',
        ];
        $validator = Validator::make($request->all(), $rules);
        if ($validator->fails()) {
            return $this->sendError($validator->errors());
        }

        $animal = $this->animalClass::find($request->query('id'));
        if (!$animal) {
            return $this->sendError(__('Animal not found'));
        }

        $calendarStart = Carbon::parse($request->start)->startOfDay();
        $calendarEnd   = Carbon::parse($request->end)->endOfDay();

        $periods = $this->animalPricePeriod::query()
            ->where('animal_id', $animal->id)
            ->where('end_date', '>=', $calendarStart)
            ->where('start_date', '<=', $calendarEnd)
            ->get();

        $events = [];

        foreach ($periods as $period) {
            $periodStart = Carbon::parse($period->start_date)->startOfDay();
            $periodEnd   = Carbon::parse($period->end_date)->startOfDay();

            for ($date = $periodStart; $date->lte($periodEnd); $date->addDay()) {
                $events[] = [
                    'id' => $period->id . '-' . $date->format('Ymd'),
                    'start' => $date->format('Y-m-d'),
                    'title' => $period->price ? number_format($period->price, 0) . ' ₽' : '—',
                    'backgroundColor' => '#27ae60',
                    'borderColor' => '#27ae60',
                    'display' => 'background',
                ];
            }
        }

        return response()->json($events);
    }


    public function store(Request $request)
    {
        $request->validate([
            'target_id' => 'required',
            'start_date' => 'required|date',
            'end_date' => 'nullable|date',
            'price' => 'nullable|numeric',
            'number' => 'nullable|integer',
            'type' => 'nullable|string', // day или range
        ]);

        $target_id = $request->input('target_id');
        $type = $request->input('type', null);
        $animal = $this->animalClass::find($target_id);

        if (!$animal) {
            return $this->sendError(__('Animal not found'));
        }

        $startDate = Carbon::parse($request->input('start_date'));
        $endDate = $type === 'range' && $request->input('end_date') ? Carbon::parse($request->input('end_date')) : $startDate;

        for ($date = $startDate->copy(); $date->lte($endDate); $date->addDay()) {
            $dateStr = $date->format('Y-m-d');

            $dayRecord = $this->animalPricePeriod::firstOrNew([
                'animal_id' => $target_id,
                'start_date' => $dateStr,
                'end_date' => $dateStr,
            ]);

            if ($type) {
                $dayRecord->price = $request->input('price', $dayRecord->price);
            }

            $dayRecord->save();
        }
        return $this->sendSuccess([], __("Update Success"));
    }
}
