<?php
namespace Modules\Hotel\Controllers;

use Carbon\Carbon;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Modules\Booking\Models\Booking;
use Modules\FrontendController;
use Modules\Hotel\DTO\RoomCalendarData;
use Modules\Hotel\Models\Hotel;
use Modules\Hotel\Models\HotelRoom;
use Modules\Hotel\Models\HotelRoomBooking;
use Modules\Hotel\Models\HotelRoomDate;
use Modules\Hotel\Requests\LoadDatesRequest;
use Modules\Hotel\Requests\StoreRoomDateRequest;
use Modules\Hotel\Services\AddDataInView;
use Modules\Hotel\Services\RoomAvailabilityService;

class AvailabilityController extends FrontendController{
    /**
     * @var string
     */
    protected string $roomClass;
    /**
     * @var string
     */
    protected string $roomDateClass;

    /**
     * @var string
     */
    protected string $bookingClass;
    /**
     * @var string
     */
    protected string $hotelClass;
    protected $currentHotel;
    /**
     * @var string
     */
    protected string $roomBookingClass;

    protected ?AddDataInView $cabinetService;
    protected RoomAvailabilityService $roomAvailabilityService;
    /**
     * @var string
     */
    protected string $indexView = 'Hotel::frontend.user.availability';

    public function __construct(AddDataInView $cabinetService, RoomAvailabilityService $roomAvailabilityService)
    {
        parent::__construct();
        $this->roomClass = HotelRoom::class;
        $this->roomDateClass = HotelRoomDate::class;
        $this->bookingClass = Booking::class;
        $this->hotelClass = Hotel::class;
        $this->roomBookingClass = HotelRoomBooking::class;
        $this->cabinetService = $cabinetService;
        $this->roomAvailabilityService = $roomAvailabilityService;
    }
    public function callAction($method, $parameters)
    {
        if(!Hotel::isEnable())
        {
            return redirect('/');
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }

    protected function hasHotelPermission($hotel_id = false): bool
    {
        if(empty($hotel_id)) return false;

        $hotel = $this->hotelClass::find($hotel_id);
        if(empty($hotel)) return false;

        if(!$this->hasPermission('hotel_update') and $hotel->author_id != Auth::id()){
            return false;
        }

        $this->currentHotel = $hotel;
        return true;
    }

    public function index(Request $request, $hotelId)
    {
        $this->checkPermission('hotel_update');
        $user = $this->cabinetService->getViewUser();
        $viewAdminCabinet = $this->cabinetService->getCabinetData();

        if(!$this->hasHotelPermission($hotelId))
        {
            abort(403);
        }

        $q = $this->roomClass::query();

        if($request->query('s')){
            $q->where('title','like','%'.$request->query('s').'%');
        }

        $q->orderBy('id','desc');
        $q->where('parent_id',$hotelId);

        $rows = $q->paginate(15);

        $current_month = strtotime(date('Y-m-01',time()));

        if($request->query('month')){
            $date = date_create_from_format('m-Y',$request->query('month'));
            if(!$date){
                $current_month = time();
            }else{
                $current_month = $date->getTimestamp();
            }
        }
        $breadcrumbs = [
            [
                'name' => __('Hotels'),
                'url'  => route('hotel.vendor.index')
            ],
            [
                'name' => __('Hotel::name',['name' => $this->currentHotel->title]),
                'url'  => route('hotel.vendor.edit', [$this->currentHotel->id])
            ],
            [
                'name'  => __('Availability'),
                'class' => 'active'
            ],
        ];
        $hotel = $this->currentHotel;
        $page_title = __('Room Availability');

        return view($this->indexView,compact('rows','breadcrumbs','current_month','page_title','request','hotel', 'user', 'viewAdminCabinet'));
    }

    public function loadDates(LoadDatesRequest $request, $hotelId): JsonResponse
    {
        if (!$this->hasHotelPermission($hotelId)) {
            return $this->sendError(__("Hotel not found"));
        }

        $dto = RoomCalendarData::fromRequest($request);
        $isSummary = $dto->id === 'summary';

        if ($isSummary) {
            $allDates = $this->roomAvailabilityService->getSummaryCalendar($hotelId, $dto);
        } else {
            $room = $this->roomClass::find($dto->id);
            if (!$room) {
                return $this->sendError(__('room not found'));
            }

            $allDates = $this->roomAvailabilityService->getRoomCalendar($room, $dto);
        }

        return response()->json(array_values($allDates));
    }


    public function store(StoreRoomDateRequest $request, $hotelId): JsonResponse
    {
        if(!$this->hasHotelPermission($hotelId))
        {
            return $this->sendError(__("Hotel not found"));
        }

        $target_id = $request->input('target_id');
        $room = $this->roomClass::find($target_id);

        if(empty($room)){
            return $this->sendError(__('Room not found'));
        }

        if(!$this->hasPermission('hotel_manage_others')){

            if($this->currentHotel->author_id != Auth::id()){
                return $this->sendError("You do not have permission to access it");
            }
        }

        $dayOfWeek = $request->input("day_of_week_select",[]);

        $postData = $request->input();

        $period = periodDate($request->input('start_date'),$request->input('end_date'));
        foreach ($period as $dt){
            $date = $this->roomDateClass::where('start_date',$dt->format('Y-m-d'))->where('target_id',$target_id)->first();

            if(empty($date)){
                $date = new $this->roomDateClass();
                $date->target_id = $target_id;
            }
            $postData['start_date'] = $dt->format('Y-m-d H:i:s');
            $postData['end_date'] = $dt->format('Y-m-d H:i:s');

            // Убеждаемся, что number передается, даже если это 0
            if (!isset($postData['number'])) {
                $postData['number'] = $room->number;
            }
            // Преобразуем в int, чтобы 0 не считался пустым
            $postData['number'] = (int)($postData['number'] ?? $room->number);

            $date->fillByAttr([
                'start_date','end_date','price',
                'is_instant','active',
                'number'
            ],$postData);

            if(empty($dayOfWeek)){
                $date->save();
            }elseif(in_array(date('N', strtotime($dt->format('Y-m-d H:i:s')) ),$dayOfWeek)){
                $date->save();
            }
        }

        return $this->sendSuccess([],__("Update Success"));
    }
}
