<?php
namespace Modules\Hotel\Controllers;

use App\Http\Controllers\Controller;
use Carbon\Carbon;
use Carbon\CarbonPeriod;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Support\Facades\Log;
use Modules\Animals\Models\Animal;
use Modules\Booking\Models\BookedDay;
use Modules\Hotel\Models\Hotel;
use Illuminate\Http\Request;
use Modules\Hotel\Models\HotelRoomBooking;
use Modules\Hotel\Models\HotelRoomDate;
use Modules\Location\Models\Location;
use Modules\Location\Models\LocationCategory;
use Modules\Review\Models\Review;
use Modules\Core\Models\Attributes;
use DB;

class HotelController extends Controller
{
    protected $hotelClass;
    protected $locationClass;
    protected $roomDateClass;
    /**
     * @var string
     */
    private $locationCategoryClass;

    public function __construct(Hotel $hotel)
    {
        $this->hotelClass = $hotel;
        $this->locationClass = Location::class;
        $this->locationCategoryClass = LocationCategory::class;
        $this->roomDateClass = new HotelRoomDate();
    }
    public function callAction($method, $parameters)
    {
        if(!Hotel::isEnable())
        {
            return redirect('/');
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }

    public function index(Request $request)
    {
        $layout = setting_item("hotel_layout_search", 'normal');
        if ($request->query('_layout')) {
            $layout = $request->query('_layout');
        }
        $is_ajax = $request->query('_ajax');
        $for_map = $request->query('_map',$layout === 'map');

        if(!empty($request->query('limit'))){
            $limit = $request->query('limit');
        }else{
            $limit = !empty(setting_item("hotel_page_limit_item"))? setting_item("hotel_page_limit_item") : 9;
        }

        $startInput = $request->input('start');
        $endInput   = $request->input('end');

        if ($startInput && $endInput) {
            $start = Carbon::parse($startInput)->startOfDay();
            $end   = Carbon::parse($endInput)->endOfDay();

            $query = $this->hotelClass->search($request->input());
            $hotelsCollection = collect($query->get());

            $hotelsCollection = $this->filterHotelsByAvailability($hotelsCollection, $start, $end);


//            $roomCount = (int) $request->input('room');
//            if ($roomCount > 0) {
//                $hotelsCollection = $this->filterHotelsByRoomCount($hotelsCollection, $roomCount, $start, $end);
//            }

            $guestCount = (int) $request->input('adults');
            if ($guestCount > 0) {
               $hotelsCollection = $this->filterHotelsByGuestCountAndAvailability($hotelsCollection, $guestCount, $start, $end);
            }
        } else {
            $hotelsCollection = collect($this->hotelClass::query()->get());
        }


        $perPage = $limit;
        $currentPage = LengthAwarePaginator::resolveCurrentPage();

        $list = new LengthAwarePaginator(
            $hotelsCollection->forPage($currentPage, $perPage),
            $hotelsCollection->count(),
            $perPage,
            $currentPage,
            [
                'path'  => request()->url(),
                'query' => request()->query(),
            ]
        );

        $markers = [];
        if ($for_map && $list->count()) {
            foreach ($list as $row) {
                $markers[] = [
                    "id"      => $row->id,
                    "title"   => $row->title,
                    "lat"     => (float)$row->map_lat,
                    "lng"     => (float)$row->map_lng,
                    "gallery" => $row->getGallery(true),
                    "infobox" => view('Hotel::frontend.layouts.search.loop-grid', ['row' => $row,'disable_lazyload'=>1,'wrap_class'=>'infobox-item'])->render(),
                    'marker' => get_file_url(setting_item("hotel_icon_marker_map"),'full') ?? url('images/icons/png/pin.png'),
                ];
            }
        }
        $data = [
            'rows' => $list,
            'layout'=>$layout
        ];
        if ($is_ajax) {
            return $this->sendSuccess([
                "markers" => $markers,
                'fragments'=>[
                    '.ajax-search-result'=>view('Hotel::frontend.ajax.search-result'.($for_map ? '-map' : ''), $data)->render(),
                    '.result-count'=>$list->total() > 1 ? __(":count hotels found",['count'=>$list->total()]) : __(":count hotel found",['count'=>$list->total()]),
                    '.count-string'=> $list->total() ? __("Showing :from - :to of :total Hotels",["from"=>$list->firstItem(),"to"=>$list->lastItem(),"total"=>$list->total()]) : ''
                ]
            ]);
        }
        $data = [
            'rows'               => $list,
            'list_location'      => $this->locationClass::where('status', 'publish')->limit(1000)->with(['translation'])->get()->toTree(),
            'list_animals'      => Animal::where('status', 'publish')->limit(1000)->with(['translation'])->get(),
            'hotel_min_max_price' => $this->hotelClass::getMinMaxPrice(),
            'markers'            => $markers,
            "blank" => setting_item('search_open_tab') == "current_tab" ? 0 : 1 ,
            "seo_meta"           => $this->hotelClass::getSeoMetaForPageList()
        ];
        $data['attributes'] = Attributes::where('service', 'hotel')->orderBy("position","ASC")->with(['terms'=>function($query){
            $query->withCount('hotel');
        },'translation'])->get();
        $data['layout'] = $layout;

        if ($layout == "map") {
            $data['body_class'] = 'has-search-map';
            $data['html_class'] = 'full-page';
            return view('Hotel::frontend.search-map', $data);
        }
        return view('Hotel::frontend.search', $data);
    }

    public function filterHotelsByAvailability($hotels, Carbon $start, Carbon $end)
    {
        return $hotels->filter(function ($hotel) use ($start, $end) {

            foreach ($hotel->rooms as $room) {

                $period = CarbonPeriod::create($start, $end);
                $isRoomAvailable = true;

               $customDates = $this->roomDateClass::query()
                   ->where('target_id', $room->id)
                   ->whereBetween('start_date', [$start->format('Y-m-d'), $end->format('Y-m-d')])
                   ->get()
                   ->keyBy(fn($row) => (new \Carbon\Carbon($row->start_date))->toDateString());

                $bookings = $room->getBookingsInRange($start, $end);

                foreach ($period as $date) {
                    $dateKey = $date->format('Y-m-d');

                    $baseNumber = $room->number;
                    if (isset($customDates[$dateKey]) && $customDates[$dateKey]->number !== null) {
                        $baseNumber = (int)$customDates[$dateKey]->number;
                    }

                    $occupied = 0;
                    foreach ($bookings as $booking) {
                        $bookingPeriod = periodDate($booking->start_date, Carbon::parse($booking->end_date)->subDay(), false);
                        foreach ($bookingPeriod as $bDate) {
                            if ($bDate->format('Y-m-d') === $dateKey) {
                                $occupied += $booking->number;
                            }
                        }
                    }

                    $freeRooms = max($baseNumber - $occupied, 0);
                    if ($freeRooms <= 0) {
                        $isRoomAvailable = false;
                        break;
                    }
                }

                if ($isRoomAvailable) {
                    return true;
                }
            }

            return false;
        });
    }

    protected function filterHotelsByRoomCount($hotels, int $roomCount, $start, $end)
    {
        $start = Carbon::parse($start)->startOfDay();
        $end   = Carbon::parse($end)->startOfDay();

        return $hotels->filter(function ($hotel) use ($roomCount, $start, $end) {

            $totalRooms = $hotel->rooms->sum('number');

            if ($totalRooms < $roomCount) {
                return false;
            }

            for ($date = $start->copy(); $date->lt($end); $date->addDay()) {

                $bookedRooms = HotelRoomBooking::query()
                    ->whereIn('room_id', $hotel->rooms->pluck('id'))
                    ->whereDate('start_date', '<=', $date)
                    ->whereDate('end_date', '>', $date)
                    ->sum('number');

                $freeRooms = $totalRooms - $bookedRooms;

                if ($freeRooms < $roomCount) {
                    return false;
                }
            }

            return true;
        });
    }

    protected function filterHotelsByGuestCountAndAvailability($hotels, int $guestCount, Carbon $start, Carbon $end)
    {
        $periodStart = $start->copy()->startOfDay();
        $periodEnd   = $end->copy()->subDay()->startOfDay();
        $periodDates = [];

        for ($date = $periodStart->copy(); $date <= $periodEnd; $date->addDay()) {
            $periodDates[] = $date->format('Y-m-d');
        }

        return $hotels->filter(function ($hotel) use ($guestCount, $periodDates, $periodStart, $periodEnd) {

            $totalCapacity = 0;

            foreach ($hotel->rooms as $room) {
                $roomDates = DB::table('bc_hotel_room_dates')
                    ->where('target_id', $room->id)
                    ->whereIn(DB::raw('DATE(start_date)'), $periodDates)
                    ->get()
                    ->keyBy(function ($item) {
                        return date('Y-m-d', strtotime($item->start_date));
                    });

                $bookings = $room->getBookingsInRange($periodStart, $periodEnd);

                $dailyAvailable = [];

                foreach ($periodDates as $date) {
                    if (isset($roomDates[$date])) {
                        $number = (int)$roomDates[$date]->active ? (int)$roomDates[$date]->number : 0;
                    } else {
                        $number = (int)$room->number;
                    }

                    $occupied = 0;
                    foreach ($bookings as $booking) {
                        $bookingStart = Carbon::parse($booking->start_date)->format('Y-m-d');
                        $bookingEnd   = Carbon::parse($booking->end_date)->subDay()->format('Y-m-d');
                        if ($date >= $bookingStart && $date <= $bookingEnd) {
                            $occupied += $booking->number;
                        }
                    }

                    $freeRooms = max($number - $occupied, 0);
                    $dailyAvailable[] = $freeRooms;
                }

                $minRooms = !empty($dailyAvailable) ? min($dailyAvailable) : 0;
                $totalCapacity += $minRooms * $room->adults;
            }
            return $totalCapacity >= $guestCount;
        });
    }

    public function detail(Request $request, $slug)
    {
        $row = $this->hotelClass::where('slug', $slug)->with(['location','translation','hasWishList'])->first();
        $hotelId = $row->id;
        if ( empty($row) or !$row->hasPermissionDetailView()) {
            return redirect('/');
        }

        $adminbar_buttons = [];

        if(is_admin()){
            $adminbar_buttons[] = ['label' => __('Edit Hotel'), 'url' => route('hotel.admin.edit',['id' => $row->id]), 'icon' => 'edit'];
        }

        $translation = $row->translate();
        $relatedQuery = $row->getRelated();
        $hotel_related = $relatedQuery ? $relatedQuery->take(4)->get() : [];
        $review_list = $row->getReviewList();
        $data = [
            'row'          => $row,
            'translation'       => $translation,
            'hotel_related' => $hotel_related,
            'location_category'=>$this->locationCategoryClass::where("status", "publish")->with('location_category_translations')->get(),
            'list_animals' => Animal::whereHas('hotels', function($query) use ($hotelId) {
                $query->where('hotel_id', $hotelId);
            })
                ->with(['translation', 'hotels' => function($q) use ($hotelId) {
                    $q->where('hotel_id', $hotelId);
                }])
                ->limit(1000)
                ->get(),
            'booking_data' => $row->getBookingData(),
            'review_list'  => $review_list,
            'seo_meta'  => $row->getSeoMetaWithTranslation(app()->getLocale(),$translation),
            'body_class'=>'is_single',
            'breadcrumbs'       => [
                [
                    'name'  => __('Hotel'),
                    'url'  => route('hotel.search'),
                ],
            ],
            'adminbar_buttons' => $adminbar_buttons
        ];
        $data['breadcrumbs'] = array_merge($data['breadcrumbs'],$row->locationBreadcrumbs());
        $data['breadcrumbs'][] = [
            'name'  => $translation->title,
            'class' => 'active'
        ];

        $this->setActiveMenu($row);
        return view('Hotel::frontend.detail', $data);
    }

    public function checkAvailability(){
        $hotel_id = \request('hotel_id');
        $adults = \request('adults');
        if(\request()->input('firstLoad') == "false") {
            $rules = [
                'hotel_id'   => 'required',
                'start_date' => 'required:date_format:Y-m-d',
                'end_date'   => 'required:date_format:Y-m-d',
                'adults'     => 'required',
            ];
            $validator = \Validator::make(request()->all(), $rules);
            if ($validator->fails()) {
                return $this->sendError($validator->errors()->all());
            }

//            if(strtotime(\request('end_date')) - strtotime(\request('start_date')) < DAY_IN_SECONDS){
//                return $this->sendError(__("Dates are not valid"));
//            }
            if(strtotime(\request('end_date')) - strtotime(\request('start_date')) > 30*DAY_IN_SECONDS){
                return $this->sendError(__("Maximum day for booking is 30"));
            }
        }

        $hotel = $this->hotelClass::find($hotel_id);
        if(empty($hotel_id) or empty($hotel)){
            return $this->sendError(__("Hotel not found"));
        }

        if(\request()->input('firstLoad') == "false") {
            $numberDays = abs(strtotime(\request('end_date')) - strtotime(\request('start_date'))) / 86400;
            if(!empty($hotel->min_day_stays) and  $numberDays < $hotel->min_day_stays){
                return $this->sendError(__("You must to book a minimum of :number days",['number'=>$hotel->min_day_stays]));
            }

            if(!empty($hotel->min_day_before_booking)){
                $minday_before = strtotime("today +".$hotel->min_day_before_booking." days");
                if(  strtotime(\request('start_date')) < $minday_before){
                    return $this->sendError(__("You must book the service for :number days in advance",["number"=>$hotel->min_day_before_booking]));
                }
            }
        }

        $rooms = $hotel->getRoomsAvailability(request()->input());

        $requestedAdults = (int) $adults;
        $totalCapacity = 0;

        foreach ($rooms as $room) {
            $room_adults = (int) ($room['adults'] ?? 0);
            $numRooms    = (int) ($room['number'] ?? 0);

            $roomCapacity = $room_adults * $numRooms;
            $totalCapacity += $roomCapacity;
        }

        if ($totalCapacity < $requestedAdults) {
            return $this->sendSuccess([
                'rooms'=>[]
            ]);
        }

            return $this->sendSuccess([
            'rooms'=>$rooms
        ]);
    }
}
